language: php
php: 8.1

before_script:
  - composer install
  - composer dump-autoload --dev

script:
  - vendor/bin/phpunit tests

notifications:
  slack: dragonflyrg:w3hYXjTOZjrmBGQuszMILN7K#opensource_notify
