#!/usr/bin/env php
<?php declare(strict_types=1);
/**
 * Neuron Job Scheduler
 * Usage:
 * Infinite polling: vendor/bin/schedule
 * Single polling: vendor/bin/schedule --poll
 */
require __DIR__ . '/../../../vendor/autoload.php';

Scheduler(
        Boot( __DIR__.'/../../../config' ),
        $argv
);
